version: "3.8"
services:
  # task-app:
  #   image: task-app
  #   build:
  #     context: ./Website/Task-App
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:4200
  #   container_name: task-app
  #   restart: unless-stopped
  # task-api:
  #   image: task-api
  #   build:
  #     context: ./API
  #     dockerfile: ./TaskAPI/Dockerfile
  #   ports:
  #     - 5000:5000
  #   container_name: task-api
  #   restart: unless-stopped
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8080:8081